// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvndabodftlkdjscchjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2bmRhYm9kZnRsa2Rqc2NjaGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MzUxNTIsImV4cCI6MjA2MTIxMTE1Mn0.844ksSNC2DP0NIrq1282AydzqJkAGdrCFtxJ1YiXn7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);